GPUS: [0]
WORKERS: 4
PRINT_FREQ: 100

DATASET:
  TYPE: aerial
  DATASET: Drone-Anomaly/{Dataset Name : Exp "Bike_Roundabout" }
  ROOT: 'Datasets'
  NUM_FRAMES: 5
  FRAME_STEPS: 2
  LOWER_BOUND: 100
  JUMP : [2,3,4,5]
  PSEUDO_ANOMALY_PROB: 0.015

TRAIN:
  BATCH_SIZE_PER_GPU: 8
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 120
  RESUME: true
  OPTIMIZER: 'lion'
  LR_TYPE: 'multistep'
  LR: 0.00002
  LR_STEP: [80,100]

TEST:
  BATCH_SIZE_PER_GPU: 1

MODEL:
  NAME: 'Drone-Guard'
  INIT_WEIGHTS: true
  IMAGE_SIZE:
    - 256
    - 256
  MEMORY_SIZE: 5
  ENCODED_FRAMES: 4
  DECODED_FRAMES: 0
  EXTRA:
    FINAL_CONV_KERNEL: 3